apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache 
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
      tier: frontend
  template:
    metadata:
      labels:
        app: apache
        tier: fronted
    spec:
      containers:
      - name: php-apache
        image: borahuho/k8s-apache-demo
        ports:
        - containerPort: 80
