---
- hosts: web
  become: true
  tasks:
  - name: Install prerequisites
    apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
    loop: [ 'aptitude' ]
  
  - name: ensure nginx is at the latest version
    apt: name=nginx state=latest
    become: yes
  
  - name: Install php Packages
    apt: name={{ item }} update_cache=yes state=latest
    loop: ['php', 'php-fpm', 'libapache2-mod-php','php-mysql','php-cgi']
  
  - name: start nginx
    service:
      name: nginx
      state: started
    become: yes

  - name: copy the nginx config file and restart nginx
    copy:
      src: dynamic.cfg
      dest: /etc/nginx/sites-available/dynamic.cfg
    become: yes

  - name: create symlink
    file:
      src: /etc/nginx/sites-available/dynamic.cfg
      dest: /etc/nginx/sites-enabled/default
      state: link
    become: yes

  - name: copy the content of the web site
    copy:
      src: "dynamic-site/"
      dest: "/home/student/dynamic-site"

  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: yes

  - name: "UFW - Allow HTTP on port 80"
    ufw:
      rule: allow
      port: "80"
      proto: tcp
    become: yes






